on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Publish Ubuntu release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: build
        run: cargo build --all --release && strip target/release/libsnip_lookup.so && mv target/release/libsnip_lookup.so lua/snip_lookup.so

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          path: "lua"
          filename: "snip-lookup-linux.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            snip-lookup-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: Publish MacOS release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: build
        run: cargo build --all --release && mv target/release/libsnip_lookup.dylib lua/snip_lookup.so

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          path: "lua"
          filename: "snip-lookup-mac-x86_64.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            snip-lookup-mac-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac-arm64:
    name: Publish MacOS arm64 release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: build
        run: cargo build --all --release --target aarch64-apple-darwin && mv target/aarch64-apple-darwin/release/libsnip_lookup.dylib lua/snip_lookup.so

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: "tar"
          path: "lua"
          filename: "snip-lookup-mac-arm64.tar.gz"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            snip-lookup-mac-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
